chore: refix formatting

diff --git a/.github/workflows/first-workflow.yaml b/.github/workflows/first-workflow.yaml
--- a/.github/workflows/first-workflow.yaml
+++ b/.github/workflows/first-workflow.yaml
@@ -2,16 +2,16 @@ name: First workflow
 on: push
 
 jobs:
-    echo-hello:
-        runs-on: ubuntu-latest
-        steps:
-            - name: hello world
-              run: echo 'hello worl'
-    echo-goodbye:
-        runs-on: ubuntu-latest
-        steps:
-            - name: goodbye world
-              run: |
-                echo 'i will fail'
-                exit 1
+  echo-hello:
+      runs-on: ubuntu-latest
+      steps:
+          - name: hello world
+            run: echo 'hello worl'
+  echo-goodbye:
+      runs-on: ubuntu-latest
+      steps:
+          - name: goodbye world
+            run: |
+              echo 'i will fail'
+              exit 1
             
