add failed job to workflow

diff --git a/.github/workflows/first-workflow.yaml b/.github/workflows/first-workflow.yaml
--- a/.github/workflows/first-workflow.yaml
+++ b/.github/workflows/first-workflow.yaml
@@ -7,4 +7,11 @@ jobs:
         steps:
             - name: hello world
               run: echo 'hello worl'
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: goodbye world
+              run: |
+                echo 'i will fail'
+                exit 1
             
